export default [
  {
    key: '0',
    id: 410,
    wxDepartmentId: 1,
    name: '快乐魔时',
    nameEn: '',
    parentId: 0,
    children: [
      {
        key: '0-0',
        type: 'department',
        id: 411,
        wxDepartmentId: 3,
        name: '香拉某酒店1',
        nameEn: '',
        children: [
          {
            key: '0-0-0',
            type: 'department',
            id: 412,
            wxDepartmentId: 4,
            name: '酒店1餐饮部门',
            nameEn: '',
            children: [
              {
                key: '0-0-0-0',
                type: 'user',
                isLeaf: true,
                id: 1222,
                userId: 'SunJiaMin',
                name: '孙佳敏',
                alias: '',
                position: '',
                email: '',
                mobile: '18702180013',
                avatar:
                  'http://wework.qpic.cn/bizmail/R2KgCcXlxxViazzgyCPZcsDWnMkOtI7BuTIkMm6yWBFsZtpA6JWujDQ/0',
                roleName: '管理员',
                roleCode: 'admin',
                departmentId: [412],
              },
              {
                key: '0-0-0-1',
                type: 'user',
                isLeaf: true,
                id: 1232,
                userId: 'XiaoJieYun',
                name: '肖洁云',
                alias: 'Joyce Siu',
                position: 'Manager，Test Dept',
                email: '',
                mobile: '13826499536',
                avatar:
                  'http://wework.qpic.cn/bizmail/snFQIIZnOupEaVcb9iatBGLy4VI3HdlnOq7WrCHvl8H43vTsK3HAWKA/0',
                roleName: '超级管理员',
                roleCode: 'super_admin',
                departmentId: [410, 411, 412, 413, 414, 416],
              },
              {
                key: '0-0-0-2',
                type: 'user',
                isLeaf: true,
                id: 1215,
                userId: 'wlw',
                name: '王立位',
                alias: '',
                position: '',
                email: '',
                mobile: '18810277472',
                avatar:
                  'http://wework.qpic.cn/bizmail/rbSrM1lTX2B306hVqc6EEbKSrYIoF3060jZicsYhW33hAkbXlc5zzjQ/0',
                roleName: '超级管理员',
                roleCode: 'super_admin',
                departmentId: [410, 411, 412],
              },
            ],
          },
          {
            key: '0-0-1',
            type: 'user',
            isLeaf: true,
            id: 1216,
            userId: 'cfe7385ed75ecd2d21112eb44b36ae7b',
            name: 'Jia Wang',
            alias: 'yamiyo',
            position: '企业微信后台职务最多展示多少个字',
            email: '',
            mobile: '13466622785',
            avatar:
              'http://wework.qpic.cn/bizmail/FRuCFNdErQxQdRwibHGwxRQxwLz9UyGfNMfQiaNOic7rsPVw5fNfrNSTQ/0',
            roleName: '管理员',
            roleCode: 'admin',
            departmentId: [410, 411],
          },
          {
            key: '0-0-2',
            type: 'user',
            isLeaf: true,
            id: 1232,
            userId: 'XiaoJieYun',
            name: '肖洁云',
            alias: 'Joyce Siu',
            position: 'Manager，Test Dept',
            email: '',
            mobile: '13826499536',
            avatar:
              'http://wework.qpic.cn/bizmail/snFQIIZnOupEaVcb9iatBGLy4VI3HdlnOq7WrCHvl8H43vTsK3HAWKA/0',
            roleName: '超级管理员',
            roleCode: 'super_admin',
            departmentId: [410, 411, 412, 413, 414, 416],
          },
          {
            key: '0-0-3',
            type: 'user',
            isLeaf: true,
            id: 1235,
            userId: 'FangXiaoChun',
            name: '方晓纯',
            alias: '',
            position: '',
            email: '',
            mobile: '13642638682',
            avatar:
              'http://wework.qpic.cn/bizmail/KzqFXCIiaR1Ga2KNYjJ0NJ961dHr4nFTU5unukMFqic12sgiaVPTw9Kkg/0',
            roleName: '超级管理员',
            roleCode: 'super_admin',
            departmentId: [410, 411, 413],
          },
          {
            key: '0-0-4',
            type: 'user',
            isLeaf: true,
            id: 1215,
            userId: 'wlw',
            name: '王立位',
            alias: '',
            position: '',
            email: '',
            mobile: '18810277472',
            avatar:
              'http://wework.qpic.cn/bizmail/rbSrM1lTX2B306hVqc6EEbKSrYIoF3060jZicsYhW33hAkbXlc5zzjQ/0',
            roleName: '超级管理员',
            roleCode: 'super_admin',
            departmentId: [410, 411, 412],
          },
        ],
      },
      {
        key: '0-1',
        type: 'department',
        id: 413,
        wxDepartmentId: 11,
        name: '香拉某酒店2',
        nameEn: '',
        children: [
          {
            key: '0-1-0',
            type: 'department',
            id: 414,
            wxDepartmentId: 12,
            name: '酒店2客房部门',
            nameEn: '',
            children: [
              {
                key: '0-1-0-0',
                type: 'user',
                isLeaf: true,
                id: 1232,
                userId: 'XiaoJieYun',
                name: '肖洁云',
                alias: 'Joyce Siu',
                position: 'Manager，Test Dept',
                email: '',
                mobile: '13826499536',
                avatar:
                  'http://wework.qpic.cn/bizmail/snFQIIZnOupEaVcb9iatBGLy4VI3HdlnOq7WrCHvl8H43vTsK3HAWKA/0',
                roleName: '超级管理员',
                roleCode: 'super_admin',
                departmentId: [410, 411, 412, 413, 414, 416],
              },
              {
                key: '0-1-0-1',
                type: 'user',
                isLeaf: true,
                id: 1225,
                userId: 'sharon',
                name: '张玲',
                alias: 'Sharon Zhang',
                position: 'Manager，Digital Marketing',
                email: '',
                mobile: '15201965685',
                avatar:
                  'http://wework.qpic.cn/bizmail/zmJX1iaqtjkdpjEaJFtwe8Ooy7RKDLtNDoghxGtdzoicicaASdCXOgbHA/0',
                roleName: '管理员',
                roleCode: 'admin',
                departmentId: [413, 414],
              },
            ],
          },
          {
            key: '0-1-1',
            type: 'user',
            isLeaf: true,
            id: 1220,
            userId: 'LiMengLong',
            name: '李梦龙',
            alias: '',
            position: '',
            email: '',
            mobile: '13810902078',
            avatar: 'https://wework.qpic.cn/wwpic/673861_W0FS2rxbTrODoLt_1649674485/0',
            roleName: '管理员',
            roleCode: 'admin',
            departmentId: [413],
          },
          {
            key: '0-1-2',
            type: 'user',
            isLeaf: true,
            id: 1226,
            userId: 'ec1125fea3cfbd2cf1e903b462889d6d',
            name: '陆碧云（Ruby）',
            alias: 'Ruby',
            position: 'XXX经理',
            email: '',
            mobile: '15021486796',
            avatar:
              'http://wework.qpic.cn/wwhead/duc2TvpEgSQykrhF5Jh51Hibiam7jBY1QfbhVy73yVpOoibibcMZTUjxY6BlCkDPdp4f1nSmib2DmDUo/0',
            roleName: '管理员',
            roleCode: 'admin',
            departmentId: [410, 413],
          },
          {
            key: '0-1-3',
            type: 'user',
            isLeaf: true,
            id: 1233,
            userId: 'ChenXiXi',
            name: '陈茜茜',
            alias: '',
            position: '',
            email: '',
            mobile: '18002288680',
            avatar:
              'http://wework.qpic.cn/bizmail/9icpBHlHJ1AHFCLPP76zdxq3AFuu8lrVIt6Pgo25OGO8jyrQgfHQ8iaQ/0',
            roleName: 'ddd',
            roleCode: '',
            departmentId: [413],
          },
          {
            key: '0-1-4',
            type: 'user',
            isLeaf: true,
            id: 1235,
            userId: 'FangXiaoChun',
            name: '方晓纯',
            alias: '',
            position: '',
            email: '',
            mobile: '13642638682',
            avatar:
              'http://wework.qpic.cn/bizmail/KzqFXCIiaR1Ga2KNYjJ0NJ961dHr4nFTU5unukMFqic12sgiaVPTw9Kkg/0',
            roleName: '超级管理员',
            roleCode: 'super_admin',
            departmentId: [410, 411, 413],
          },
          {
            key: '0-1-5',
            type: 'user',
            isLeaf: true,
            id: 1221,
            userId: 'ZhangHaiHui',
            name: '张海辉',
            alias: '活动时',
            position: '',
            email: '',
            mobile: '13826426062',
            avatar:
              'http://wework.qpic.cn/bizmail/Oibs2biaQL9tf6LvUasfb6UgYmq4znnJebbxFzSNtGUZ4DTXfticMUUKg/0',
            roleName: '部门管理员',
            roleCode: 'department_admin',
            departmentId: [413],
          },
          {
            key: '0-1-6',
            type: 'user',
            isLeaf: true,
            id: 1225,
            userId: 'sharon',
            name: '张玲',
            alias: 'Sharon Zhang',
            position: 'Manager，Digital Marketing',
            email: '',
            mobile: '15201965685',
            avatar:
              'http://wework.qpic.cn/bizmail/zmJX1iaqtjkdpjEaJFtwe8Ooy7RKDLtNDoghxGtdzoicicaASdCXOgbHA/0',
            roleName: '管理员',
            roleCode: 'admin',
            departmentId: [413, 414],
          },
          {
            key: '0-1-7',
            type: 'user',
            isLeaf: true,
            id: 1232,
            userId: 'XiaoJieYun',
            name: '肖洁云',
            alias: 'Joyce Siu',
            position: 'Manager，Test Dept',
            email: '',
            mobile: '13826499536',
            avatar:
              'http://wework.qpic.cn/bizmail/snFQIIZnOupEaVcb9iatBGLy4VI3HdlnOq7WrCHvl8H43vTsK3HAWKA/0',
            roleName: '超级管理员',
            roleCode: 'super_admin',
            departmentId: [410, 411, 412, 413, 414, 416],
          },
        ],
      },
      {
        key: '0-2',
        type: 'department',
        id: 415,
        wxDepartmentId: 13,
        name: '部门3-GSO',
        nameEn: '',
        children: [
          {
            key: '0-2-0',
            type: 'user',
            isLeaf: true,
            id: 1227,
            userId: 'WangJia',
            name: '王佳',
            alias: '',
            position: '',
            email: '',
            mobile: '18618110037',
            avatar:
              'http://wework.qpic.cn/bizmail/FNEmkLVDia0PrYDIecE3KsXXVAY5o5Y9RqVP4DLpjYe0AuAcZRIiaicLg/0',
            roleName: '管理员',
            roleCode: 'admin',
            departmentId: [415],
          },
          {
            key: '0-2-1',
            type: 'user',
            isLeaf: true,
            id: 1228,
            userId: 'BeiFengNuan',
            name: '北风暖',
            alias: '',
            position: '华北区负责人',
            email: '',
            mobile: '13249392000',
            avatar:
              'http://wework.qpic.cn/bizmail/ic4dN4XlOX5ZJxyibHb4GZ3TT0RMmSD69kCOMYLE5khibw5Kkc5xAnDZw/0',
            roleName: '部门管理员',
            roleCode: 'department_admin',
            departmentId: [415],
          },
          {
            key: '0-2-2',
            type: 'user',
            isLeaf: true,
            id: 1229,
            userId: 'vicky',
            name: '樊维婧',
            alias: '浦东香格里拉Vicky Fan',
            position: 'Managers , Digital Marketing, China Marketing',
            email: '',
            mobile: '18516089093',
            avatar:
              'http://wework.qpic.cn/bizmail/WNaprWKRiaLyib66KibHiazibPe9ib3417D7xkfmQf6vtRG4Vlgbkib72vN3w/0',
            roleName: '管理员',
            roleCode: 'admin',
            departmentId: [415],
          },
        ],
      },
      {
        key: '0-3',
        type: 'department',
        id: 416,
        wxDepartmentId: 14,
        name: '酒店3',
        nameEn: '',
        children: [
          {
            key: '0-3-0',
            type: 'user',
            isLeaf: true,
            id: 1232,
            userId: 'XiaoJieYun',
            name: '肖洁云',
            alias: 'Joyce Siu',
            position: 'Manager，Test Dept',
            email: '',
            mobile: '13826499536',
            avatar:
              'http://wework.qpic.cn/bizmail/snFQIIZnOupEaVcb9iatBGLy4VI3HdlnOq7WrCHvl8H43vTsK3HAWKA/0',
            roleName: '超级管理员',
            roleCode: 'super_admin',
            departmentId: [410, 411, 412, 413, 414, 416],
          },
        ],
      },
      {
        key: '0-4',
        type: 'user',
        isLeaf: true,
        id: 1215,
        userId: 'wlw',
        name: '王立位',
        alias: '',
        position: '',
        email: '',
        mobile: '18810277472',
        avatar:
          'http://wework.qpic.cn/bizmail/rbSrM1lTX2B306hVqc6EEbKSrYIoF3060jZicsYhW33hAkbXlc5zzjQ/0',
        roleName: '超级管理员',
        roleCode: 'super_admin',
        departmentId: [410, 411, 412],
      },
      {
        key: '0-5',
        type: 'user',
        isLeaf: true,
        id: 1216,
        userId: 'cfe7385ed75ecd2d21112eb44b36ae7b',
        name: 'Jia Wang',
        alias: 'yamiyo',
        position: '企业微信后台职务最多展示多少个字',
        email: '',
        mobile: '13466622785',
        avatar:
          'http://wework.qpic.cn/bizmail/FRuCFNdErQxQdRwibHGwxRQxwLz9UyGfNMfQiaNOic7rsPVw5fNfrNSTQ/0',
        roleName: '管理员',
        roleCode: 'admin',
        departmentId: [410, 411],
      },
      {
        key: '0-6',
        type: 'user',
        isLeaf: true,
        id: 1217,
        userId: 'foxglove',
        name: '丁敏',
        alias: 'Min Ding',
        position: 'Manager, Product Design, TDC',
        email: '',
        mobile: '17681448860',
        avatar:
          'http://wework.qpic.cn/bizmail/HY6zhH2HA5loORgvPAPxnKicdAD8UNvdvRtzzQLqicffuVaLITFicaU8w/0',
        roleName: '管理员',
        roleCode: 'admin',
        departmentId: [410],
      },
      {
        key: '0-7',
        type: 'user',
        isLeaf: true,
        id: 1218,
        userId: 'Jingjingzhou',
        name: '周静',
        alias: '浦东香格里拉 Jing Zhou',
        position: 'AVP, Digital Marketing, China Marketing',
        email: 'jing.zhou@shangri-la.com',
        mobile: '13917667875',
        avatar:
          'https://wework.qpic.cn/wwhead/duc2TvpEgSSdsPInfahzx3ptwPMQibSLWTiaHyHA21MJzNyiaydYJn8FC7lsL66KxjTlA7VtovcrYs/0',
        roleName: '管理员',
        roleCode: 'admin',
        departmentId: [410],
      },
      {
        key: '0-8',
        type: 'user',
        isLeaf: true,
        id: 1219,
        userId: 'rc',
        name: 'RC',
        alias: 'Raymond CW Chan',
        position: 'Manager, Strategy & Business Transformation',
        email: '',
        mobile: '',
        avatar:
          'http://wework.qpic.cn/bizmail/wCTZ6QugWZt025mlSry2RWpUMuaXbKSr6x1BDicrXPEA3hCIryT0libA/0',
        roleName: '管理员',
        roleCode: 'admin',
        departmentId: [410],
      },
      {
        key: '0-9',
        type: 'user',
        isLeaf: true,
        id: 1223,
        userId: 'WuXiaoXiang',
        name: '吴小翔',
        alias: '',
        position: '',
        email: '',
        mobile: '13533909197',
        avatar:
          'https://wework.qpic.cn/bizmail/J1kzFSTuMgvpQhuZTjFVh9rbXX2ShGQ3RpRriaa2dW7c4Zactzk9Sibw/0',
        roleName: '管理员',
        roleCode: 'admin',
        departmentId: [410],
      },
      {
        key: '0-10',
        type: 'user',
        isLeaf: true,
        id: 1226,
        userId: 'ec1125fea3cfbd2cf1e903b462889d6d',
        name: '陆碧云（Ruby）',
        alias: 'Ruby',
        position: 'XXX经理',
        email: '',
        mobile: '15021486796',
        avatar:
          'http://wework.qpic.cn/wwhead/duc2TvpEgSQykrhF5Jh51Hibiam7jBY1QfbhVy73yVpOoibibcMZTUjxY6BlCkDPdp4f1nSmib2DmDUo/0',
        roleName: '管理员',
        roleCode: 'admin',
        departmentId: [410, 413],
      },
      {
        key: '0-11',
        type: 'user',
        isLeaf: true,
        id: 1230,
        userId: 'SunJinQuan',
        name: '孙金权',
        alias: '',
        position: '',
        email: '',
        mobile: '18514236526',
        avatar:
          'https://wework.qpic.cn/bizmail/SfOaaCWFK9cmPzzia3Fhu6RFNPiattcuicH9v75Cb2z5m0IicuAnQ5JYlw/0',
        roleName: '超级管理员',
        roleCode: 'super_admin',
        departmentId: [410],
      },
      {
        key: '0-12',
        type: 'user',
        isLeaf: true,
        id: 1232,
        userId: 'XiaoJieYun',
        name: '肖洁云',
        alias: 'Joyce Siu',
        position: 'Manager，Test Dept',
        email: '',
        mobile: '13826499536',
        avatar:
          'http://wework.qpic.cn/bizmail/snFQIIZnOupEaVcb9iatBGLy4VI3HdlnOq7WrCHvl8H43vTsK3HAWKA/0',
        roleName: '超级管理员',
        roleCode: 'super_admin',
        departmentId: [410, 411, 412, 413, 414, 416],
      },
      {
        key: '0-13',
        type: 'user',
        isLeaf: true,
        id: 1234,
        userId: 'caijinyi',
        name: '蔡锦仪',
        alias: '',
        position: '',
        email: '',
        mobile: '17329968874',
        avatar: 'https://wework.qpic.cn/wwpic/443916_DCjWfYryTmGXbNU_1649838419/0',
        roleName: '',
        roleCode: '',
        departmentId: [410],
      },
      {
        key: '0-14',
        type: 'user',
        isLeaf: true,
        id: 1235,
        userId: 'FangXiaoChun',
        name: '方晓纯',
        alias: '',
        position: '',
        email: '',
        mobile: '13642638682',
        avatar:
          'http://wework.qpic.cn/bizmail/KzqFXCIiaR1Ga2KNYjJ0NJ961dHr4nFTU5unukMFqic12sgiaVPTw9Kkg/0',
        roleName: '超级管理员',
        roleCode: 'super_admin',
        departmentId: [410, 411, 413],
      },
      {
        key: '0-15',
        type: 'user',
        isLeaf: true,
        id: 1236,
        userId: 'LiHui',
        name: '李辉',
        alias: '',
        position: '产品经理',
        email: '',
        mobile: '13011805800',
        avatar:
          'http://wework.qpic.cn/bizmail/1jPj8jNh00NQv8yUky9icB5lT29oibek3Cib3ibxxCmJcapIDiakibUObZag/0',
        roleName: '超级管理员',
        roleCode: 'super_admin',
        departmentId: [410],
      },
    ],
  },
];
